name: Sigma Validation

on:
pull_request:
    branches:
      - master

 workflow_dispatch:



jobs:
  sigma-rules-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Sigma rules
        uses: SigmaHQ/sigma-rules-validator@v1
         paths:
      - "rules/**.yml"
