name: Validate Sigma rules

on:
  push:
    branches:
      - "*"
    paths:
      - "rules/**.yml"
  pull_request:
    branches:
      - master
    paths:
      - "rules/**.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sigma-rules-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Sigma rules
        uses: SigmaHQ/sigma-rules-validator@v1
        with:
          paths: |-
            ./rules
